[package]
name = "nss-userhosts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
strip = true
codegen-units = 1
lto = "fat"

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
